Levantoso.Web/Controllers/LevantosoController.cs
using Levantoso.Domain.Excel;
using Levantoso.Domain.Models;
using Levantoso.Web.ViewModel;
using System.Collections.Generic;
using System.Web;
using System.Web.Mvc;

namespace Levantoso.Web.Controllers
{
    public class LevantosoController : Controller
    {
        public ActionResult Index() => View();

        public ActionResult AbrirGrupo(string nomeGrupo)
        {
            return View("_Grid", new List<GrupoModel> { new GrupoModel(nomeGrupo) });
        }

        [HttpPost]
        public ActionResult NovaLinhaGrid(ItemLevantamentoModel item)
        {
            return View("_RowGrid", item);
        }

        [HttpPost]
        public ActionResult ExportarParaExcel(ExportarExcelViewModel exportacao)
        {
            var excelContent = GeradorExcel.GerarPeloWeb(exportacao.Grupos);
            return File(excelContent, "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet", exportacao.NomeArquivo + ".xlsx");
        }

        [HttpPost]
        public ActionResult Upload(HttpPostedFileBase file)
        {
            var grupos = LeitorExcel.Processar(file?.InputStream);
            return View("_Grid", grupos);
        }

        [HttpPost]
        public ActionResult Load(IEnumerable<GrupoModel> grupos)
        {
            return View("_Grid", grupos);
        }
    }
}

Levantoso.Web/Views/Levantoso/Index.cshtml
@{
    ViewBag.Title = "title";
    Layout = null;
}

<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
<link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
<script src="~/scripts/jquery-3.7.1.js"></script>

<div id="container-tudo" class="container-sm">
    <div id="div-grid-tabela"></div>
    <div id="divs-botoes" class="row">
        <div id="div-botao-gerar" class="col">
            <button type="button" class="btn btn-primary" data-bs-toggle="modal" data-bs-target="#modalNovoGrupo"
                    onclick="levantoso.atribuirFocoNoInputDaModal('nomeGrupo')">Criar Tabela</button>
        </div>
        <div id="div-buton" class="col">
            <button type="button" class="btn btn-primary" data-bs-toggle="modal" data-bs-target="#modalExportarLevantamento"
                    onclick="levantoso.atribuirFocoNoInputDaModal('nomeArquivo')">Gerar Arquivo</button>
        </div>
        
        <div id="div-buton" class="col">
            <button type="button" class="btn btn-danger" onclick="levantoso.limparTudo()">Limpar tudo</button>
        </div>
    </div>
    <div class="form-group" id="div-file" style="padding: 20px;">
        <input type="file" class="form-control" id="dataFile" onchange="levantoso.arquivo.importar()" name="file" />
    </div>
</div>

<div class="modal fade" id="modalNovoGrupo" tabindex="-1" aria-labelledby="modalNovoGrupo" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title">Escolha o Nome da Tabela</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Fechar"></button>
            </div>
            <div class="modal-body">
                <label>Nome:</label>
                <input id="nomeGrupo" type="text"/>
            </div>
            <div class="modal-footer">
                <button type="submit" class="btn btn-primary" data-bs-dismiss="modal" onclick="levantoso.grupo.inserir()">Confirmar</button>
            </div>
        </div>
    </div>
</div>

<div class="modal fade" id="modalEditarGrupo" tabindex="-1" aria-labelledby="modalEditarGrupo" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title">Escolha o novo nome da Tabela</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Fechar"></button>
            </div>
            <div class="modal-body">
                <div class="form-group col-sm">
                    <label id="nomeAntigoGrupo" data-value></label>
                </div>
                <div class="form-group col-sm">
                    <label>Nome:</label>
                    <input id="novoNomeGrupo" type="text"/>
                </div>
            </div>
            <div class="modal-footer">
                <button type="submit" class="btn btn-primary" data-bs-dismiss="modal" onclick="levantoso.grupo.editar()">Confirmar</button>
            </div>
        </div>
    </div>
</div>

<div class="modal fade" id="modalExportarLevantamento" tabindex="-1" aria-labelledby="modalExportarLevantamento" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title">Escolha o Nome do Arquivo</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Fechar"></button>
            </div>
            <div class="modal-body">
                <label>Nome:</label>
                <input id="nomeArquivo" type="text" />
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-primary" data-bs-dismiss="modal" onclick="levantoso.arquivo.gerar()">Salvar</button>
            </div>
        </div>
    </div>
</div>

<div class="modal fade" id="modalTrocarItemGrupo" tabindex="-1" aria-labelledby="modalTrocarItemGrupo" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title">Escolha o grupo de destino</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Fechar"></button>
            </div>
            <div class="modal-body">
                <label>Grupo:</label>
                <select class="form-control input grupos-disponiveis"></select>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-primary" data-bs-dismiss="modal" onclick="levantoso.item.mudarGrupo()">Mudar Grupo</button>
            </div>
        </div>
    </div>
</div>

<script src="~/lib/levantoso.js?d=@DateTime.Now.Ticks"></script>
<link rel="stylesheet" href="~/lib/levantoso.css?d=@DateTime.Now.Ticks">
<script>
    levantoso.init({
        urls: {
            abrirGrupo: '@Url.Action("AbrirGrupo")',
            novaLinhaGrid: '@Url.Action("NovaLinhaGrid")',
            exportarParaExcel: '@Url.Action("ExportarParaExcel")',
            importandoArquivo: '@Url.Action("Upload")',
            load: '@Url.Action("Load")',
        }
    });

</script>

Levantoso.Web/Views/Levantoso/_Grid.cshtml
@using Levantoso.Domain.Lists
@model IEnumerable<Levantoso.Domain.Models.GrupoModel>

@{
    ViewBag.Title = "title";
    Layout = null;
}
<div id="container">
    <div id="grid-tabela">
        @if (Model != null)
        {
            foreach (var grupo in Model)
            {
                <div class="quadro-grupo" style="margin-top: 35px;">
                    <div style="display: flex">
                        <h3 style="width: 93%" class="titulo-grupo">@grupo.NomeGrupo</h3>
                        <button type="button" class="btn btn-primary" onclick="levantoso.grupo.abrirModalEditar(this)" data-bs-toggle="modal" data-bs-target="#modalEditarGrupo">
                            <i class="material-icons">edit</i>
                        </button>
                        <button type="button" class="btn btn-danger" onclick="levantoso.grupo.remover(this)">
                            <i class="material-icons">delete</i>
                        </button>
                    </div>
                    <table class="table table-striped tabela-grupo" id="@grupo.NomeGrupo">
                        <thead>
                            <tr>
                                <th scope="col">Tipo Oper.</th>
                                <th scope="col">Item</th>
                                <th scope="col">Complexidade</th>
                                <th scope="col">Descrição</th>
                                <th scope="col"></th>
                                <th scope="col"></th>
                                <th scope="col"></th>
                            </tr>
                        </thead>
                        <tbody>
                            @if (grupo.Itens != null)
                            {
                                foreach (var item in grupo.Itens)
                                {
                                    @Html.Partial("_RowGrid", item)
                                }
                            }

                        </tbody>
                    </table>
                    <div id="grid-form">
                        <form id="form-tabela">
                            <div class="container-sm row">
                                <div class="form-group col-sm">
                                    <label>T.O</label>
                                    <select class="form-control input tipo-operacao" data-table="@grupo.NomeGrupo" required>
                                        @foreach (var itemCombo in TipoOperacaoList.ComboValues)
                                        {
                                            <option value="@itemCombo.Value">@itemCombo.Text</option>
                                        }
                                    </select>
                                </div>
                                <div class="form-group col-sm">
                                    <label>Item</label>
                                    <select class="form-control input item" required>
                                        @foreach (var itemCombo in ItemList.ComboValues)
                                        {
                                            <option value="@itemCombo.Value">@itemCombo.Text</option>
                                        }
                                    </select>
                                </div>
                                <div class="form-group col-sm">
                                    <label>Complexidade</label>
                                    <select class="form-control input complexidade" required>
                                        @foreach (var complexidade in ComplexidadeList.ComboValues)
                                        {
                                            <option value="@complexidade.Value">@complexidade.Text</option>
                                        }
                                    </select>
                                </div>
                                <div class="form-group">
                                    <label>Descrição</label>
                                    <textarea class="form-control input descricao" required placeholder="Digite uma Descrição" rows="3"></textarea>
                                </div>
                                <div class="form-group" id="btn-adicionar">
                                    <button type="button" class="btn btn-primary" onclick="levantoso.item.inserir(this);">
                                        <i class="material-icons">add</i>
                                    </button>
                                </div>
                            </div>
                        </form>
                    </div>
                </div>
            }
        }
    </div>
</div>

Levantoso.Web/Views/Levantoso/_RowGrid.cshtml
@model Levantoso.Domain.Models.ItemLevantamentoModel
@{
    Layout = null;
}

<tr style="font-size: 15px;">
    <td class="td-no-description tipo-operacao" data-value="@Model.TipoOperacao.Value">@Model.TipoOperacao.Text</td>
    <td class="td-no-description item" data-value="@Model.Item.Value">@Model.Item.Text</td>
    <td class="td-no-description complexidade" data-value="@Model.Complexidade.Value">@Model.Complexidade.Text</td>
    <td class="descricao">@Model.Descricao</td>
    <td class="td-btn">
        <button class="btn btn-grid" onclick="levantoso.item.editar(this)"><i class="material-icons">edit</i></button>
    </td>
    <td class="td-btn">
        <button class="btn btn-grid" onclick="levantoso.abrirEscolhaNovoGrupo(this)"
                data-bs-toggle="modal" data-bs-target="#modalTrocarItemGrupo"><i class="material-icons">swap_vert</i></button>
    </td>
    <td class="td-btn">
        <button class="btn btn-grid" onclick="levantoso.item.remover(this)"><i class="material-icons">delete</i></button>
    </td>
</tr>

Levantoso.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    <script src="~/scripts/bootstrap.js"></script>
    <script src="~/scripts/jquery-3.7.1.js"></script>
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Application name", "Index", "Levantoso", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                </ul>
            </div>
        </div>
    </div>

    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>